name: Debian 11 CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  install-debian:
    runs-on: ubuntu-22.04
    name: on Debian 11
    steps:
      - name: Test run server
        uses: UISSH/install-script@latest
