name: Debian 11 CI

on :
  push :
    branches : [ "main" ]
  pull_request :
    branches : [ "main" ]

jobs :
  install-debian :
    runs-on : ubuntu-22.04
    container: jrei/systemd-debian:bullseye
    name : on Debian 11
    steps :
      - uses : actions/checkout@v3
      - name : Init
        run : bash install.sh
      - name : Deploy
        run : |
          python3 main.py --email=root@root.com --db_password=root --password=root --ci
          /usr/local/uissh/backend/venv/bin/python3 /usr/local/uissh/backend/manage.py check