name: Install Debian 11 Test

on: [ push ]

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    name: Test install backend on Debian 11
    steps:
      - name: Test run server
        uses: UISSH/install-script@latest


